FROM teracy/angular-cli

ENV HOME=/home/ec2-user/nodejs
ENV APP_NAME=duvana-front

# before switching to user we need to set permission properly
COPY ./$APP_NAME/package.json $HOME/$APP_NAME/
RUN groupadd -r nodejs && \
    useradd -r -g nodejs -d /home/nodejs -s /sbin/nologin nodejs && \
    chown -R nodejs:nodejs $HOME

USER nodejs
WORKDIR $HOME/$APP_NAME

RUN npm install --unsafe-perm=true && \
    npm cache clean

CMD ["ng", "serve", "--host", "0.0.0.0" ]
